import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useNavigate } from "react-router-dom";
import { useMutation } from "@tanstack/react-query";
import { apiClient } from "@/lib/api/client";
import { Button } from "@base-ui/react";
import { FormInput } from "@/components/form/FormInput";
import AuthCard from "../component/AuthCard";
import PasswordInput from "../component/passwordInput";
import { AuthCheckboxRow } from "../component/AuthCheckBox";
import { AuthDivider } from "../component/AuthDivider";
import SocialAuthButton from "../component/SocialAuthButton";
import AuthSwitchLink from "../component/AuthSwitchLink";
import { createAccountSchema, type CreateAccountFormValues } from "../schemas/createAccountSchema";